name: Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature!
        Please describe your idea below.

  - type: textarea
    id: problem
    attributes:
      label: Problem or Use Case
      description: What problem does this feature solve? What's the use case?
      placeholder: |
        I frequently need to restore window positions for different scenarios 
        (home office vs. meeting room), but currently I can only save one snapshot.
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How do you think this should work?
      placeholder: |
        Allow multiple snapshot slots (e.g., 5 slots) that can be selected 
        from the menu bar or via hotkeys (⌃⌘1, ⌃⌘2, etc.)
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions?
      placeholder: |
        I tried using separate user accounts, but switching is too slow.
    validations:
      required: false

  - type: dropdown
    id: priority
    attributes:
      label: How important is this feature to you?
      options:
        - "Nice to have"
        - "Would significantly improve my workflow"
        - "Critical - I can't use Tsubame without it"
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other information, mockups, or examples
    validations:
      required: false
